version: '3.7'

services:
  notifier:
    image: aixxe.net/notifier:latest
    environment:
      NOTIFY_KEYWORD: 'search term goes here'
      NOTIFY_WEBHOOK_URL: 'https://discord.com/api/webhooks/.../...'
    volumes:
      - state:/srv/app/state
    restart: unless-stopped

volumes:
  state: